Demo2_WebApp/Demo2_WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Demo2_WebApp.Indexes;
using Demo2_WebApp.Infrastructure;
using Demo2_WebApp.Models;
using Demo2_WebApp.Models.ViewModels;

namespace Demo2_WebApp.Controllers
{
    public class HomeController : RavenDbController
    {
        public ActionResult Index()
        {
            var tasksPerPerson = RavenSession
                .Query<TasksCount_ForPerson.Result, TasksCount_ForPerson>()
                .OrderBy(r => r.OwnerName)
                .ToList();
            return View(new HomeIndexViewModel(){TasksPerPerson = tasksPerPerson});
        }

        public ActionResult Search(string query)
        {
            var homeSearchViewModel = new HomeSearchViewModel();
            var result = RavenSession.Advanced.LuceneQuery<Task, Tasks>().Search("Name", query).Take(10);
            homeSearchViewModel.Tasks = result.ToList();
            homeSearchViewModel.Query = query;
            homeSearchViewModel.TotalResults = result.QueryResult.TotalResults;
            return View(homeSearchViewModel);
        }
    }
}

Demo2_WebApp/Demo2_WebApp/Controllers/ProjectController.cs
using System.Web.Mvc;
using Demo2_WebApp.Indexes;
using Demo2_WebApp.Infrastructure;
using Demo2_WebApp.Models;
using System.Linq;
using Demo2_WebApp.Models.ViewModels;
using Raven.Client.Linq;

namespace Demo2_WebApp.Controllers
{
    public class ProjectController : RavenDbController
    {
        public ActionResult Index(int page = 1)
        {
            var viewModel = new ProjectIndexViewModel();

            RavenQueryStatistics stats;
            var projects = RavenSession.Query<ActivitiesCount_PerProject.Result,ActivitiesCount_PerProject>()
                .Statistics(out stats)
                .Skip((page-1) * 100)
                .Take(100)
                .ToList();

            viewModel.TotalResults = stats.TotalResults;

            viewModel.Projects = projects.Select(result => new ProjectIndexViewModel.ProjectViewModel()
                                                                {
                                                                    ProjectName = result.ProjectName,
                                                                    ProjectId = result.ProjectId,
                                                                    NumberOfActivities = result.NumberOfActivities
                                                                });
            viewModel.Page = page;
            return View(viewModel);
        }

        public ActionResult Details(int id)
        {
            var project = RavenSession.Load<Project>(id);
            return View(project);
        }
    }
}

Demo2_WebApp/Demo2_WebApp/Controllers/TaskController.cs
using System.Web.Mvc;
using Demo2_WebApp.Infrastructure;
using Raven.Abstractions.Data;

namespace Demo2_WebApp.Controllers
{
    public class TaskController : RavenDbController
    {
        [HttpPost]
        public ActionResult MarkAsDone(string id)
        {
            RavenSession.Advanced.DatabaseCommands.Patch(id, new []
                                                                 {
                                                                     new PatchRequest()
                                                                         {
                                                                             Type = PatchCommandType.Set,
                                                                             Name = "Done",
                                                                             Value = true
                                                                         }, 
                                                                 });
            return Json(new {status="ok"});
        }

        [HttpPost]
        public ActionResult MarkAsNotDone(string id)
        {
            RavenSession.Advanced.DatabaseCommands.Patch(id, new []
                                                                 {
                                                                     new PatchRequest()
                                                                         {
                                                                             Type = PatchCommandType.Set,
                                                                             Name = "Done",
                                                                             Value = false
                                                                         }, 
                                                                 });
            return Json(new {status="ok"});
        }
    }
}

Demo2_WebApp/Demo2_WebApp/Views/Home/Index.cshtml
@model Demo2_WebApp.Models.ViewModels.HomeIndexViewModel

@{
    ViewBag.Title = "Home Page";
}
@section featured {
    <section class="featured">
    <div class="content-wrapper">
        <hgroup class="title">
            <h1>@ViewBag.Title.</h1>
            <h2>@ViewBag.Message</h2>
        </hgroup>
        <p>
            
        </p>
    </div>
</section>
}
<section class="features">
    <section class="feature">
        <ul>
            @foreach(var personAndNumberOfTasks in Model.TasksPerPerson)
            {
                <li>@Model.Persons[@personAndNumberOfTasks.OwnerId].Name - @personAndNumberOfTasks.Count</li> 
            }
        </ul>
    </section>
    <section class="feature">
        <ul>
            <li>
                @Html.ActionLink("Todos os projectos", "Index", "Project")
            </li>
            <li>
                @Html.ActionLink("Projecto 1", "Details", "Project", new { id = 1 }, new object())
            </li>
            <li>
                @Html.ActionLink("Projecto 2", "Details", "Project", new { id = 2 }, new object())
            </li>
        </ul>
    </section>
    <section class="feature">
 
    </section>
</section>

Demo2_WebApp/Demo2_WebApp/Views/Home/Search.cshtml
@model Demo2_WebApp.Models.ViewModels.HomeSearchViewModel

@{
}

<h2>Searching for "@Model.Query"</h2>

<ul>
@foreach (var task in Model.Tasks)
{
    <li><strong>@task.Name</strong> - @if (task.Done)
                                      { <text><span class="task_mark_as_not_done" data-taskid="@task.Id">✓</span></text> }
                                      else
                                      {
                                          <text><span class="task_mark_as_done" data-taskid="@task.Id">☐</span></text>
                                      } ( @task.OwnerName )</li>
}
</ul>
<p>
    @Model.TotalResults results found.
</p>
<script type="text/javascript">
    $(function () {
        $(".task_mark_as_done").click(function () {
            var taskId = $(this).data("taskid");
            $.post("@Url.Action("MarkAsDone","Task")", { id: taskId }, function(data) {
                window.location.reload(true);
            }, "json");
        });
        $(".task_mark_as_not_done").click(function () {
            var taskId = $(this).data("taskid");
            $.post("@Url.Action("MarkAsNotDone","Task")", { id: taskId }, function(data) {
                window.location.reload(true);
            }, "json");
        });
    });
</script>